default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username:
    password:
    socket: /tmp/mysql.sock

production:
    <<: *default
    database: blog_development
    username: <%= ENV['DB_USERNAME']%>
    password: <%= ENV['DB_PASSWORD']%>

development:
    <<: *default
    database: blog_development
    username: <%= ENV['DB_USERNAME']%>
    password: <%= ENV['DB_PASSWORD']%>
