default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
    <<: *default
    database: blog_development
    username: <%= ENV['DB_USERNAME']%>
    password: <%= ENV['DB_PASSWORD']%>
    socket: /var/lib/mysql/mysql.sock

development:
    <<: *default
    database: blog_development
    username: <%= ENV['DEV_DB_USERNAME']%>
    password: <%= ENV['DEV_DB_PASSWORD']%>
    socket: /tmp/mysql.sock
